### ISSUE TITLE
Question: how do you change the code of the streamlit app?

### ISSUE THREAD

**Issue by david26694** [snehankekre/st-codespaces#1]
I want to have my own app and still use streamlit in codespaces, do you know how can I modify the app and not use the default one?

![image](https://github.com/snehankekre/st-codespaces/assets/22721584/62f75d3f-a608-44a5-9019-499de029d2e4)

**Comment by snehankekre** [comment]
Hey @david26694 👋 

> do you know how can I modify the app and not use the default one?

Certainly! Add your app to the root of the repo, and modify the `postStartCommand` in `devcontainer.json` to run your app.
Say your app is `app.py`. 

Replace the following:

```json
"postStartCommand": "streamlit hello",
```

with:

```json
"postStartCommand": "streamlit run app.py",
```

**Comment by david26694** [comment]
ah right, my bad

**Comment by david26694** [comment]
thanks!
